package com.sanzu.pojo;

import java.io.Serializable;
import java.util.Date;

public class YongHu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.yonghuming
     *
     * @mbg.generated
     */
    private String yonghuming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.mima
     *
     * @mbg.generated
     */
    private String mima;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.xingming
     *
     * @mbg.generated
     */
    private String xingming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.xingbie
     *
     * @mbg.generated
     */
    private String xingbie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.chushengriqi
     *
     * @mbg.generated
     */
    private Date chushengriqi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.wenhuachengdu
     *
     * @mbg.generated
     */
    private String wenhuachengdu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.lianxifangshi
     *
     * @mbg.generated
     */
    private String lianxifangshi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.suoshuzhuanye
     *
     * @mbg.generated
     */
    private String suoshuzhuanye;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.suozaibum
     *
     * @mbg.generated
     */
    private String suozaibum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.gongzuozhiwei
     *
     * @mbg.generated
     */
    private String gongzuozhiwei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.jiatingdizhi
     *
     * @mbg.generated
     */
    private String jiatingdizhi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.zhengzhimianmao
     *
     * @mbg.generated
     */
    private String zhengzhimianmao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.ruzhishijian
     *
     * @mbg.generated
     */
    private Date ruzhishijian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.id
     *
     * @return the value of yonghu.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.id
     *
     * @param id the value for yonghu.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.yonghuming
     *
     * @return the value of yonghu.yonghuming
     *
     * @mbg.generated
     */
    public String getYonghuming() {
        return yonghuming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.yonghuming
     *
     * @param yonghuming the value for yonghu.yonghuming
     *
     * @mbg.generated
     */
    public void setYonghuming(String yonghuming) {
        this.yonghuming = yonghuming == null ? null : yonghuming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.mima
     *
     * @return the value of yonghu.mima
     *
     * @mbg.generated
     */
    public String getMima() {
        return mima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.mima
     *
     * @param mima the value for yonghu.mima
     *
     * @mbg.generated
     */
    public void setMima(String mima) {
        this.mima = mima == null ? null : mima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.xingming
     *
     * @return the value of yonghu.xingming
     *
     * @mbg.generated
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.xingming
     *
     * @param xingming the value for yonghu.xingming
     *
     * @mbg.generated
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.xingbie
     *
     * @return the value of yonghu.xingbie
     *
     * @mbg.generated
     */
    public String getXingbie() {
        return xingbie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.xingbie
     *
     * @param xingbie the value for yonghu.xingbie
     *
     * @mbg.generated
     */
    public void setXingbie(String xingbie) {
        this.xingbie = xingbie == null ? null : xingbie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.chushengriqi
     *
     * @return the value of yonghu.chushengriqi
     *
     * @mbg.generated
     */
    public Date getChushengriqi() {
        return chushengriqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.chushengriqi
     *
     * @param chushengriqi the value for yonghu.chushengriqi
     *
     * @mbg.generated
     */
    public void setChushengriqi(Date chushengriqi) {
        this.chushengriqi = chushengriqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.wenhuachengdu
     *
     * @return the value of yonghu.wenhuachengdu
     *
     * @mbg.generated
     */
    public String getWenhuachengdu() {
        return wenhuachengdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.wenhuachengdu
     *
     * @param wenhuachengdu the value for yonghu.wenhuachengdu
     *
     * @mbg.generated
     */
    public void setWenhuachengdu(String wenhuachengdu) {
        this.wenhuachengdu = wenhuachengdu == null ? null : wenhuachengdu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.lianxifangshi
     *
     * @return the value of yonghu.lianxifangshi
     *
     * @mbg.generated
     */
    public String getLianxifangshi() {
        return lianxifangshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.lianxifangshi
     *
     * @param lianxifangshi the value for yonghu.lianxifangshi
     *
     * @mbg.generated
     */
    public void setLianxifangshi(String lianxifangshi) {
        this.lianxifangshi = lianxifangshi == null ? null : lianxifangshi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.suoshuzhuanye
     *
     * @return the value of yonghu.suoshuzhuanye
     *
     * @mbg.generated
     */
    public String getSuoshuzhuanye() {
        return suoshuzhuanye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.suoshuzhuanye
     *
     * @param suoshuzhuanye the value for yonghu.suoshuzhuanye
     *
     * @mbg.generated
     */
    public void setSuoshuzhuanye(String suoshuzhuanye) {
        this.suoshuzhuanye = suoshuzhuanye == null ? null : suoshuzhuanye.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.suozaibum
     *
     * @return the value of yonghu.suozaibum
     *
     * @mbg.generated
     */
    public String getSuozaibum() {
        return suozaibum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.suozaibum
     *
     * @param suozaibum the value for yonghu.suozaibum
     *
     * @mbg.generated
     */
    public void setSuozaibum(String suozaibum) {
        this.suozaibum = suozaibum == null ? null : suozaibum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.gongzuozhiwei
     *
     * @return the value of yonghu.gongzuozhiwei
     *
     * @mbg.generated
     */
    public String getGongzuozhiwei() {
        return gongzuozhiwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.gongzuozhiwei
     *
     * @param gongzuozhiwei the value for yonghu.gongzuozhiwei
     *
     * @mbg.generated
     */
    public void setGongzuozhiwei(String gongzuozhiwei) {
        this.gongzuozhiwei = gongzuozhiwei == null ? null : gongzuozhiwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.jiatingdizhi
     *
     * @return the value of yonghu.jiatingdizhi
     *
     * @mbg.generated
     */
    public String getJiatingdizhi() {
        return jiatingdizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.jiatingdizhi
     *
     * @param jiatingdizhi the value for yonghu.jiatingdizhi
     *
     * @mbg.generated
     */
    public void setJiatingdizhi(String jiatingdizhi) {
        this.jiatingdizhi = jiatingdizhi == null ? null : jiatingdizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.zhengzhimianmao
     *
     * @return the value of yonghu.zhengzhimianmao
     *
     * @mbg.generated
     */
    public String getZhengzhimianmao() {
        return zhengzhimianmao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.zhengzhimianmao
     *
     * @param zhengzhimianmao the value for yonghu.zhengzhimianmao
     *
     * @mbg.generated
     */
    public void setZhengzhimianmao(String zhengzhimianmao) {
        this.zhengzhimianmao = zhengzhimianmao == null ? null : zhengzhimianmao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.ruzhishijian
     *
     * @return the value of yonghu.ruzhishijian
     *
     * @mbg.generated
     */
    public Date getRuzhishijian() {
        return ruzhishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.ruzhishijian
     *
     * @param ruzhishijian the value for yonghu.ruzhishijian
     *
     * @mbg.generated
     */
    public void setRuzhishijian(Date ruzhishijian) {
        this.ruzhishijian = ruzhishijian;
    }
}