package com.sanzu.pojo;

import java.util.List;
import java.util.Map;

public interface YongHuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghu
     *
     * @mbg.generated
     */
    int insert(YongHu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghu
     *
     * @mbg.generated
     */
    int insertSelective(YongHu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghu
     *
     * @mbg.generated
     */
    YongHu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YongHu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YongHu record);

    YongHu selectByYongHuMing(String yonghuming);
    List<YongHu> selectYongHu();
}