package com.sanzu.pojo;

import java.io.Serializable;

public class ZhiWei implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwei.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwei.zhiweimingcheng
     *
     * @mbg.generated
     */
    private String zhiweimingcheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwei.zhiweimiaoshu
     *
     * @mbg.generated
     */
    private String zhiweimiaoshu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwei.chaxunquanxina
     *
     * @mbg.generated
     */
    private String chaxunquanxina;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwei.kaohequanxian
     *
     * @mbg.generated
     */
    private String kaohequanxian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwei.tongjichaxun
     *
     * @mbg.generated
     */
    private String tongjichaxun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwei.quanxianguanli
     *
     * @mbg.generated
     */
    private String quanxianguanli;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhiwei.houtaiguanli
     *
     * @mbg.generated
     */
    private String houtaiguanli;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwei.id
     *
     * @return the value of zhiwei.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwei.id
     *
     * @param id the value for zhiwei.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwei.zhiweimingcheng
     *
     * @return the value of zhiwei.zhiweimingcheng
     *
     * @mbg.generated
     */
    public String getZhiweimingcheng() {
        return zhiweimingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwei.zhiweimingcheng
     *
     * @param zhiweimingcheng the value for zhiwei.zhiweimingcheng
     *
     * @mbg.generated
     */
    public void setZhiweimingcheng(String zhiweimingcheng) {
        this.zhiweimingcheng = zhiweimingcheng == null ? null : zhiweimingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwei.zhiweimiaoshu
     *
     * @return the value of zhiwei.zhiweimiaoshu
     *
     * @mbg.generated
     */
    public String getZhiweimiaoshu() {
        return zhiweimiaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwei.zhiweimiaoshu
     *
     * @param zhiweimiaoshu the value for zhiwei.zhiweimiaoshu
     *
     * @mbg.generated
     */
    public void setZhiweimiaoshu(String zhiweimiaoshu) {
        this.zhiweimiaoshu = zhiweimiaoshu == null ? null : zhiweimiaoshu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwei.chaxunquanxina
     *
     * @return the value of zhiwei.chaxunquanxina
     *
     * @mbg.generated
     */
    public String getChaxunquanxina() {
        return chaxunquanxina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwei.chaxunquanxina
     *
     * @param chaxunquanxina the value for zhiwei.chaxunquanxina
     *
     * @mbg.generated
     */
    public void setChaxunquanxina(String chaxunquanxina) {
        this.chaxunquanxina = chaxunquanxina == null ? null : chaxunquanxina.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwei.kaohequanxian
     *
     * @return the value of zhiwei.kaohequanxian
     *
     * @mbg.generated
     */
    public String getKaohequanxian() {
        return kaohequanxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwei.kaohequanxian
     *
     * @param kaohequanxian the value for zhiwei.kaohequanxian
     *
     * @mbg.generated
     */
    public void setKaohequanxian(String kaohequanxian) {
        this.kaohequanxian = kaohequanxian == null ? null : kaohequanxian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwei.tongjichaxun
     *
     * @return the value of zhiwei.tongjichaxun
     *
     * @mbg.generated
     */
    public String getTongjichaxun() {
        return tongjichaxun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwei.tongjichaxun
     *
     * @param tongjichaxun the value for zhiwei.tongjichaxun
     *
     * @mbg.generated
     */
    public void setTongjichaxun(String tongjichaxun) {
        this.tongjichaxun = tongjichaxun == null ? null : tongjichaxun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwei.quanxianguanli
     *
     * @return the value of zhiwei.quanxianguanli
     *
     * @mbg.generated
     */
    public String getQuanxianguanli() {
        return quanxianguanli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwei.quanxianguanli
     *
     * @param quanxianguanli the value for zhiwei.quanxianguanli
     *
     * @mbg.generated
     */
    public void setQuanxianguanli(String quanxianguanli) {
        this.quanxianguanli = quanxianguanli == null ? null : quanxianguanli.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhiwei.houtaiguanli
     *
     * @return the value of zhiwei.houtaiguanli
     *
     * @mbg.generated
     */
    public String getHoutaiguanli() {
        return houtaiguanli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhiwei.houtaiguanli
     *
     * @param houtaiguanli the value for zhiwei.houtaiguanli
     *
     * @mbg.generated
     */
    public void setHoutaiguanli(String houtaiguanli) {
        this.houtaiguanli = houtaiguanli == null ? null : houtaiguanli.trim();
    }
}